In [2]:
import csv 
import os 
import sys

In [3]:
    os.chdir(r'C:\Users\swaraj\Desktop\codes\modules\working')
    # print(i)
    
    #print (os.getcwd())
    directory = os.listdir()

In [41]:
import pandas as pd 
import numpy as np
d={}
fr=[]
csv_files = []
for files in directory:
        #print(files)
        if files.endswith(".csv"):
            csv_files.append(files)
            #print(files, "-----------------------")
            f = pd.read_csv(files)

            # print(time.time()-e1234)
            #f['file_name'] = files
            # print(f)
            d[files]=f
            fr.append(f)
            files = files[:files.index('.')]
            ([files])

In [81]:
d['commonfloor.csv'].columns=['0','area','bathrooms','text','link','title','prices','dates','owner','furnished']
d['prop.csv'].columns=['0','title','link','text','area','prices']
d['propertywala.csv'].columns=['0','title','owner','area','text','link']
d['housing.csv'].columns=['0','prices','location','furnished','owner','link','title','area']
d['sulekha.csv'].columns=['0','title','link','location','text','text1','co-ordinate','area','prices','depo','dates','owner']
d['scraped_data.csv'].columns=['0','type','prices','area','link','title','depo','furnished','location','owner']
d['magicbricks.csv'].columns=['0','text','owner','title','prices','location']

In [100]:
# d['99acers.csv']

,Unnamed: 0,link,title,prices,location,type,area,text
0,0,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Keshav...,"₹ 15,000 /monthDeposit ₹ 32000",Godrej Infinity,2 BHK2 Baths,"1,100 sq.ft. (102 sq.m.) Super built-up Area",2bhk flat for rent at prime location with all ...
1,1,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Sus,"₹ 16,000 /monthDeposit ₹ 50000",Vilas Javdekar Yashwin,2 BHK2 Baths,"1,099 sq.ft. (102 sq.m.) Super built-up Area",This is your chance to rent a 2 bhk residentia...
2,2,/3-bhk-bedroom-residential-apartments-for-rent...,3 BHK Residential Apartment for rent in Shanka...,"₹ 30,000 /monthDeposit ₹ 150000",Kalpataru Splendour,3 BHK3 Baths,"1,457 sq.ft. (135 sq.m.) Carpet Area",Looking for an affordable apartment with best ...
3,3,/4-bhk-bedroom-independent-house-for-rent-in-m...,4 Bedroom Independent House for rent in Market...,"₹ 35,000 /monthDeposit ₹ 150000",NaN,4 BHK4 Baths,"2,500 sq.ft. (232 sq.m.) Plot Area",The house of your dreams is available for rent...
4,4,/1-bhk-bedroom-residential-apartments-for-rent...,1 BHK Residential Apartment for rent in Aundh,"₹ 18,000 /monthDeposit ₹ 50000",Surobhi Park,1 BHK1 Bath,700 sq.ft. (65 sq.m.) Super built-up Area,Prime location fully furnished airy society ev...
5,5,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Chikhali,"₹ 10,000 /monthDeposit ₹ 30000",Sonigara Blue Dice,2 BHK2 Baths,"1,000 sq.ft. (93 sq.m.) Super built-up Area",Looking for an affordable apartment with best ...
6,6,/3-bhk-bedroom-residential-apartments-for-rent...,3 BHK Residential Apartment for rent in Viman ...,"₹ 38,000 /monthDeposit 3 month(s) rent",Clover Acropolis,3 BHK3 Baths,"1,530 sq.ft. (142 sq.m.) Super built-up Area",Clover acropolis is a prestigious society in v...
7,7,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Wagholi,"₹ 11,000 /monthDeposit ₹ 25000",Majestique Manhattan,2 BHK2 Baths,838 sq.ft. (78 sq.m.) Super built-up Area,I want to rent out a 2 bhk apartment available...
8,8,/3-bhk-bedroom-residential-apartments-for-rent...,3 BHK Residential Apartment for rent in Bhausa...,"₹ 22,500 /monthDeposit ₹ 50000",Vridavan Elegance,3 BHK2 Baths,"1,275 sq.ft. (118 sq.m.) Super built-up Area",Looking for an affordable apartment with best ...
9,9,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Kharadi,"₹ 18,000 /monthDeposit ₹ 50000","Giridhar Oasis, Thite Wasti , Pune",2 BHK2 Baths,"1,800 sq.ft. (167 sq.m.) Super built-up Area","All basic amenities like mall, hospital,scholl..."
10,10,/3-bhk-bedroom-residential-apartments-for-rent...,3 BHK Residential Apartment for rent in Rahatani,"₹ 23,000 /monthDeposit ₹ 70000",GK Royal Rahadki Greens Phase 2,3 BHK3 Baths,"1,600 sq.ft. (149 sq.m.) Super built-up Area",3 bhk available for rent from -11 august
11,11,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Rahatani,"₹ 17,000 /monthDeposit ₹ 60000",GK Dwarka Queens Park,2 BHK2 Baths,"1,096 sq.ft. (102 sq.m.) Super built-up Area",2 bedroom apartment in dwarka queens park avai...
12,12,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Bhosari,"₹ 17,000 /monthDeposit ₹ 38000",Landge Nestworth Chs,2 BHK2 Baths,900 sq.ft. (84 sq.m.) Super built-up Area,Fully furnished home with appliances and piped...
13,13,/1-bhk-bedroom-residential-apartments-for-rent...,1 BHK Residential Apartment for rent in Viman ...,"₹ 16,500 /month",Siddharth Modern Homes,1 BHK1 Bath,650 sq.ft. (60 sq.m.) Super built-up Area,This is a terrace flat with big terrace of 750...
14,14,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Punawale,"₹ 13,500 /monthDeposit ₹ 40000",Swaraaj Pride,2 BHK2 Baths,989 sq.ft. (92 sq.m.) Super built-up Area,Roadside facing spacious east-West facing
15,15,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Thergaon,"₹ 18,000 /monthDeposit ₹ 50000",Green Spirit,2 BHK2 Baths,"1,043 sq.ft. (97 sq.m.) Super built-up Area",Green sprit society is located in prime locati...
16,16,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Manjar...,"₹ 8,500 /monthDeposit ₹ 15000",Invidudal,2 BHK2 Baths,850 sq.ft. (79 sq.m.) Carpet Area,I want to rent out a 2 bhk apartment available...
17,17,/1-bhk-bedroom-independent-house-for-rent-in-b...,1 Bedroom Independent House for rent in Warje,"₹ 10,500 /month",Brahmachaitanya Society,1 BHK1 Bath,"7,500 sq.ft. (697 sq.m.) Plot Area",1 bhk flat is availble now near from highway a...
18,18,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Hadapsar,"₹ 17,000 /month",Kumar Park Infinia Phase 4,2 BHK2 Baths,"1,400 sq.ft. (130 sq.m.) Super built-up Area",I want to rent out a 2 bhk apartment available...
19,19,/1-bhk-bedroom-residential-apartments-for-rent...,1 BHK Residential Apartment for rent in Dhayari,"₹ 7,000 /month",Muktai Complex,1 BHK1 Bath,550 sq.ft. (51 sq.m.) Super built-up Area,I want to rent out a 1 bhk apartment available...
20,20,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Pimple...,"₹ 20,000 /month",Rose Icon,2 BHK2 Baths,920 sq.ft. (85 sq.m.) Built-up Area,I want to rent out a 2 bhk apartment available...
21,21,/2-bhk-bedroom-residential-apartments-for-rent...,2 BHK Residential Apartment for rent in Phursungi,"₹ 13,500 /monthDeposit ₹ 35000",Anand Green County,2 BHK2 Baths,920 sq.ft. (85 sq.m.) Super built-up Area,1km from sp infocity phursungi\r\n24*7 water n...
22,22,/1-bhk-bedroom-residential-apartments-for-rent...,1 BHK Residential Apartment for rent in Thite ...,"₹ 12,300 /monthDeposit ₹ 35000",M Square Dreamland,1 BHK1 Bath,550 sq.ft. (51 sq.m.) Super built-up Area,"Very nice construction. Close to school, highw..."
23,23,/1-bhk-bedroom-residential-apartments-for-rent...,1 BHK Residential Apartment for rent in Bakori,"₹ 4,000 /monthDeposit ₹ 12000",Pristine Aakanksha,1 BHK1 Bath,705 sq.ft. (66 sq.m.) Super built-up Area,I want to rent out a 1 bhk apartment available...
24,24,/5-bhk-bedroom-residential-apartments-for-rent...,5 BHK Residential Apartment for rent in JJC Co...,"₹ 90,000 /monthDeposit 3 month(s) rent",Amanora Park Town R3,5 BHK5 Baths,"2,880 sq.ft. (268 sq.m.) Super built-up Area",Qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
25,25,/5-bhk-bedroom-residential-apartments-for-rent...,5 BHK Residential Apartment for rent in JJC Co...,"₹ 90,000 /monthDeposit 3 month(s) rent",Amanora Park Town R3,5 BHK5 Baths,"2,880 sq.ft. (268 sq.m.) Super built-up Area",Qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq

In [89]:
f=[]
for k in d.keys():
    # print(k)
    # print(d[k].columns)
    f.append(d[k])

99acers.csv
Index(['Unnamed: 0', 'link', 'title', 'prices', 'location', 'type', 'area',
       'text'],
      dtype='object')
99acers2.csv
Index(['Unnamed: 0', 'link', 'title', 'prices', 'location', 'type', 'area',
       'text', 'dates'],
      dtype='object')
99acers2_pa.csv
Index(['Unnamed: 0', 'link', 'title', 'prices', 'location', 'place', 'type',
       'area', 'dates', 'names'],
      dtype='object')
commonfloor.csv
Index(['0', 'area', 'bathrooms', 'text', 'link', 'title', 'prices', 'dates',
       'owner', 'furnished'],
      dtype='object')
hjjolkkjj99acers2.csv
Index(['Unnamed: 0', 'link', 'title', 'prices', 'location', 'type', 'area',
       'dates'],
      dtype='object')
housing.csv
Index(['0', 'prices', 'location', 'furnished', 'owner', 'link', 'title',
       'area'],
      dtype='object')
magicbricks.csv
Index(['0', 'text', 'owner', 'title', 'prices', 'location'], dtype='object')
prop.csv
Index(['0', 'title', 'link', 'text', 'area', 'prices'], dtype='object')
propertywala.csv
Index(['0', 'title', 'owner', 'area', 'text', 'link'], dtype='object')
scraped_data.csv
Index(['0', 'type', 'prices', 'area', 'link', 'title', 'depo', 'furnished',
       'location', 'owner'],
      dtype='object')
sulekha.csv
Index(['0', 'title', 'link', 'location', 'text', 'text1', 'co-ordinate',
       'area', 'prices', 'depo', 'dates', 'owner'],
      dtype='object')

In [101]:
re=pd.concat(f[1:])

In [102]:
re

,Unnamed: 0,link,title,prices,location,type,area,text,dates,place,names,0,bathrooms,owner,furnished,depo,text1,co-ordinate
0,0.0,https://www.99acres.com/1-bhk-bedroom-farm-hou...,1 Bedroom Farm house in Mhow,₹ 14.04 Lac₹ 351/sq.ft.,Raya Estate,1 BHK1 Bath,"4,000 sq.ft. (372 sq.m.) Plot Area",Raya estate is a residential development of ra...,"Posted on 19th Mar, 2021 by Dealer",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,https://www.99acres.com/3-bhk-bedroom-independ...,3 Bedroom Independent House in Super Corridor,₹ 66.81 Lac,Sarthak Elite 27,3 BHK,"1,821 sq.ft. (169 sq.m.) Built-up Area",The elite 27 by sarthak estate developers is a...,"Posted on 15th Oct, 2020 by Dealer",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,https://www.99acres.com/residential-land-for-s...,Residential land / Plot in Nainod,₹ 91.99 Lac - 1.02 Cr,Emaar Continental City,NaN,"2,530-2,800 sq.ft. (235-260 sq.m.) Plot Area",Emaar continental city is a residential develo...,"Posted on 20th Mar, 2021 by Builder",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,https://www.99acres.com/residential-land-for-s...,Residential land / Plot in Nainod,₹ 91.99 Lac - 1.02 Cr,Emaar Continental City,NaN,"2,530-2,800 sq.ft. (235-260 sq.m.) Plot Area",Emaar continental city is a residential develo...,"Posted on 20th Mar, 2021 by Builder",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,https://www.99acres.com/2-bhk-bedroom-resident...,2 BHK Residential Apartment in Pipaliyahana,"₹ 36.5 - 36.5 Lac₹ 3,685/sq.ft.",Signature Heights,2 BHK2 Baths,986-996 sq.ft. (92-93 sq.m.) Carpet Area,Enjoy a blissful living experience in Signatur...,"Posted on 01st Apr, 2021 by Builder",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,NaN,https://property.sulekha.com/apartments-flats-...,1 RK Residential Apartment for Rent in Pimpri,"7,000","Pimpri,",NaN,400 Sq Feet,1 Car Parking Ground Floor (of 1 Floors) UnFur...,2019-06-29,NaN,NaN,20.0,NaN,Broker: Vision Associates,NaN,"50,000",Corporation water Drainage Facility 24*7 Power...,"18.6297811,73.7997094"
121,NaN,https://property.sulekha.com/apartments-flats-...,1 BHK Residential Apartment for Rent in Dhayari,"5,600",Benkar,NaN,550 Sq Feet,No Car Parking 3rd (of 4 Floors) UnFurnished F...,2021-05-15,NaN,NaN,21.0,NaN,Broker: Rama Enterprises,NaN,"20,000",Corporation water ATM Visitors Parking +1 Amen...,"0,0"
122,NaN,https://property.sulekha.com/apartments-flats-...,3 BHK Residential Apartment for Rent at Eterna...,for,"Undri,",NaN,1509 Sq Feet,1 Car Parking 4th (of 11 Floors) Fully Furnish...,2020-03-18,NaN,NaN,22.0,NaN,Building: Eternal Exotica Broker: Ozone Pro...,NaN,"2,000,000",24*7 Power Backup Lifts Swimming Pool +16 Amen...,"18.4566651,73.9095279"
123,NaN,https://property.sulekha.com/apartments-flats-...,2 BHK Residential Apartment for Rent at Gyanga...,"15,000",Wireless,NaN,900 Sq Feet,1 Car Parking 1st (of 5 Floors) UnFurnished Fa...,2021-04-12,NaN,NaN,23.0,NaN,Building: Gyanganga Owner: Shrikant DALVI,NaN,"50,000",Corporation water Drainage Facility Lifts +10 ...,"18.564194,73.8040924"
124,NaN,https://property.sulekha.com/apartments-flats-...,1 RK Residential Apartment for Rent at swami i...,"6,890","Hadapsar,",NaN,420 Sq Feet,No Car Parking 1st (of 4 Floors) Semi Furnishe...,2021-03-25,NaN,NaN,24.0,NaN,Building: swami Broker: Sejal Properties,NaN,"14,000",Corporation water Drainage Facility 24*7 Power...,"18.515806,73.927164"

In [103]:
re=re.drop(['Unnamed: 0','0','names'],axis=1)

In [104]:
re=re.drop(['place'],axis=1)

In [107]:
re.to_csv('data_still.csv')